# Generated by Django 3.2.21 on 2023-09-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230912_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='release_date',
            field=models.DateField(),
        ),
    ]
