# Generated by Django 3.2.21 on 2023-09-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
